### PR TITLE
chore(ci): Update renku actions to v0.4.1

### PR DESCRIPTION
**Pull request by olevski**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
/deploy

### CODE REVIEW

**Review by jachro — DISMISSED** [review]
Thanks Tasko.

**Comment by olevski** [comment]
The setup is as follows:

- if you do not provide `#persist` in the PR description (i.e. like  `/deploy #persist`) then the CI deployment is deleted after the acceptance tests complete
- if you provide `#persist` the deployment is kept until the PR is closed.
- when the PR is closed the namespace of the deployment is also deleted
- when the acceptance tests complete AND `#persist` is not used the CI deployment is deleted but the namespace is not deleted in k8s - this makes it possible to reuse the TLS secret and not hit the limits for requesting certs with letsencrypt - when the acceptance tests for the same PR are run many times
- artifacts from the acceptance tests are managed by the single (composite) test-renku action

**Review by jachro — DISMISSED** [review]

**Comment by olevski** [comment]
@jachro sorry this is the last change that was needed. No the test deployment will be deleted when the acceptance tests complete if you do not set the `#persist` flag.

**Review by jachro — APPROVED** [review]
Thanks!

**Comment by olevski** [comment]
The action is functioning as expected. The failure in the acceptance tests is a fluke and it is not affected at all by the changes in the PR. Nevertheless I will rerun the workflow so that I merge on all green.

**Pull request merged**
