### PR TITLE
Service Pack 1 :)

### PR DESCRIPTION
**Pull request by jachro**
Stress testing Graph Services unveiled a few issues. This PR addresses them:
* GitLab API has some limitations in terms of a number of request/sec from a single IP. A throttling mechanism was introduced into the services so they don't go over the limit.
* Graph Services use Postgres DB for Access Tokens storage and Event Log. They are not the only users of the DB so limiting connection were necessary to prevent from running out of connections. Configurable connection pool was introduced to address the issue.
* Graph Services deal with a mixture of asynchronous processes and batch jobs. As these processes are parallelized, there was a problem of too many threads being created which caused issues like out of memory. This PR introduces configurable thread pools to fix the issue.
* According to Jiri it seems 'renku log' can potentially hang and when that happens the process should be simply killed. I added timeout of 3 minutes for the call.
* There's no need to fetch files' content from git-lfs for triples generation. I tweaked the `triples-generator`'s `Dockerfile` to change default behaviour of `git checkout <sha>` so it doesn't pull the data.
* There was also a bug in `triples-generator` causing marking events in the Event Log as many times as parents in a commit event.
* I also tweaked both container and java memory settings for services which required that.
* I made the event history loading not be blocking the history creation call.

### CODE REVIEW

**Comment by rokroskar** [comment]
Nice, that's a lot of fixes!

A quick note about pulling from lfs - you should set the environment variable `GIT_LFS_SKIP_SMUDGE=1` to avoid pulling lfs objects on git checkout.

**Comment by jachro** [comment]
Yes, quite a few changes. They were revelling gradually once I was fixing them.
In terms of the `git-lfs` and pulling the content I achieved the same result with these two lines:
`git config --global filter.lfs.smudge "git-lfs smudge --skip %f"`
`git config --global filter.lfs.process "git-lfs filter-process --skip"`
Do you think the env variable is a better approach?

**Comment by rokroskar** [comment]
Yes those will work -- the environment variable is one line so seems easier

**Comment by jachro** [comment]
If that's doing the same I'd maybe leave these two lines in the `Dockerfile` as it seems to be a bit closer to the service and would work even if somebody just starts the service with a `docker run`.

**Comment by rokroskar** [comment]
You can set an environment variable in the `Dockerfile` as well - i'd say this is fine for the time being but we've had lots of issues in the past with LFS setup so keep that in mind.

**Comment by rokroskar** [comment]
@jachro can you give some hints as to how to test this monster PR?

**Comment by jachro** [comment]
The changes touch (if that's the proper word ;) the "non-interactive" parts of the services: the scheduler which syncs missed events with the current state in GitLab, performance, db access, configuration and logs. In general, I was testing that by dropping some initial events into the Event Log DB (as below) so the scheduler takes them as a starting point and generates all the historical events for all public repos. Then, you can look into the logs, grafana and eventually Event Log DB to verify if all worked fine.
That's for the perf/scheduler/logs testing. The second part of testing is simply to leave the Services in that state and let them working as long as possible. They will be syncing periodically with GitLab, dealing with all the in Push Events coming on user pushes and calls to the API from the UI. So sooner we deploy the changes, the better the services will be tested.
He are the events to put into the Event Log:
After sshing to the Postgres node, log in with `psql -U eventlog -d event_log` and drop the inserts:
`
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('980fa13ae114552ae9cc7c94255d83a74db42145', 79, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('d279b8276752f6da2310604c9e9e4f577a542c63', 16, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('3469bfc129791ae3e91728c03ba5a14e87547931', 44, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('a7d5444701b2e88cbf2cf3e9e58a4920091dc264', 8, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('1bda3b70fa57d8def2aac4f0a0acef10dad3f7a9', 71, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('4cec17ade2954f49a2a5cc4190fbbe7ccf89531c', 66, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('a4a751335669ef5b80ddbc7fa8fdb0bf824509cb', 21, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('4e3ad5f3b454cd836964c18bc1b0ed36e3630e48', 20, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('edcc797672b635460f875d7f3d8b28e5e18897e2', 34, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('6a35a45ddce7396d9cf8154494ada22d96656dce', 28, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('e230ae99b8a5eb3dc02d2dae9c48222f968c20eb', 22, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('f6a9da76aeed4fcb081092e2689803f0bb1aacab', 4, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('3f5447e02f73aeee0faa38dc1f7d4274d115a883', 42, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('6f9a10469066ce209593a20a2b483745bec7f3b4', 33, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('96213ad3682923b34e65e958c7a19e87dc7c884f', 69, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('db57fb09ed0de7ed3be1a3f12a60766a09f0525f', 12, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('02b5e12c62a5d15eea9b7160f4a7c620fe7e3264', 78, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('ea98d77d5942e7e6b0042b970a3274421da2ff49', 77, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('074672e930503b509fcc0b34ce40aec37981e173', 10, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('1a5c77487cf7cacae142412d8fec3bf110dfd1db', 41, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('ce57b66b0b2930c70ae2c701415c1eb8f7ac3d4e', 45, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('2c6987606f693a594c8242262717bff358b225d9', 83, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('2e716d81a1cb5eb8fdea61cea33beacb5b83a5c3', 30, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('b8af08fa0d6abca5a27c4e0dfb32b192acf889b7', 6, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('f682186898041e1ab9f24b89ac5c6dabff89e491', 65, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('4b9309919d23689e8eefc9aa8d819180107da025', 15, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('328710fef32917b5e7c5866f5b30acbfe67074c6', 72, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('743b1af1d863b6df030561a217f3d2eb72282e8c', 62, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('f6ab2ec71c088d6e98311f7a78c3ac40a9fe032d', 32, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('7e435d95241660228713401f1b91c717394cc380', 76, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('eb4c70f6b259da9ecf8bf7c3431244e76f25103c', 27, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('06b7dd6009c20ba1f469d5cb8a87c999c94c042c', 39, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
insert into event_log (event_id, project_id, status, created_date, execution_date, event_date, event_body) values ('33058732ea5689b11c3f62a984ed3f96186e650d', 85, 'NEW', '2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z', '2010-01-01T00:00:00Z', '{}');
`

**Pull request merged**
